/run/initialize
/run/printProgress 1000000
/gps/particle proton
/gps/pos/type Plane
/gps/pos/shape Square
/gps/pos/halfx 0.5 cm
/gps/pos/halfy 0.5 cm
/gps/pos/centre 0 0 -4 cm
/gps/direction 0 0 1
/gps/ene/type Arb
/gps/hist/type arb
/gps/hist/point 1.624  0.449830
/gps/hist/point 3.360  0.733382
/gps/hist/point 6.952  1.161661
/gps/hist/point 14.384  1.487248
/gps/hist/point 29.764  1.139912
/gps/hist/point 61.585  0.477126
/gps/hist/point 127.427  0.133392
/gps/hist/point 263.665  0.022484
/gps/hist/point 545.559  0.000535
/gps/hist/inter Log