/run/initialize
/gps/particle proton
/gps/pos/type Plane
/gps/pos/shape Square
/gps/pos/halfx 0.5 cm
/gps/pos/halfy 0.5 cm
/gps/pos/centre 0 0 -4 cm
/gps/direction 0 0 1
/gps/ene/type Arb
/gps/hist/type arb
/gps/hist/point 1.624  1.3
/gps/hist/point 3.360  1.2
/gps/hist/point 6.952  1.1
/gps/hist/point 14.384  1.0
/gps/hist/point 29.764  0.9
/gps/hist/point 61.585  0.8
/gps/hist/point 127.427  0.7
/gps/hist/point 263.665  0.6
/gps/hist/point 545.559  0.5
/gps/hist/point 1128.838  0.4
/gps/hist/point 2335.721  0.3
/gps/hist/point 4832.930  0.2
/gps/hist/point 10000.000  0.1
/gps/hist/inter Log